const content = {
  en: {
    home: "Home",
    explore: "Explore",
    notifications: "Notifications",
    messages: "Messages",
    bookmarks: "Bookmarks",
    lists: "Lists",
    profile: "Profile",
    more: "More",
    introplaceholder: "What’s happening",
    seachtwitter: "Search Twitter",
    trends: "Trend for you",
    trending: "Trending in Germany",
    revolution: "revolution",
    tweets: "50.4K Tweets",
    showmore: "Show more",
    youlike: "You might like",
    follow: "follow",
  },
  uz: {
    home: "Uy",
    explore: "O'rganing",
    notifications: "Bildirishnomalar",
    messages: "Xabarlar",
    bookmarks: "Xatcho'plar",
    lists: "Ro'yxatlar",
    profile: "Profil",
    more: "Ko'proq",
    introplaceholder: "Nimalar bo'lyapti",
    seachtwitter: "Twitterdan qidirish",
    trends: "Siz uchun trend",
    trending: "Germaniyada trend",
    revolution: "inqilob",
    tweets: "50.4K Tweetlar",
    showmore: "Ko'proq ko'rish",
    youlike: "Sizga yoqishi mumkin",
    follow: "kuzatish",
  },
};

export default content;
